#begin braking distance
stopping_distance: 200

#description
threshold1_low: 100
threshold2_high: 500
    
#description
threshold2_low: 1000
threshold2_high: 2000

test1: 10
test2: 20
test3: 30
test4: 40
