target_name: TESTING
target_ip: 192.168.68.119
target_port: 8187
comm_timeout_us: 1000000
packet_name: PACKET
packet_frequency: 1
group_screens: true
limits_persistence: 1
screen_update_rate: 1.0
screen_value_width: 12
screen_decimals: 4
dense_logs: false
raw_logs: true
