target_name: UDP
target_ip: 172.22.11.2
target_port: 8187
comm_timeout_us: 250000
packet_name: PACKET
packet_frequency: 10
group_screens: true
limits_persistence: 3
screen_update_rate: 1.0
screen_value_width: 12
screen_decimals: 4
dense_logs: false
raw_logs: true